import time

from codrone_edu.drone import *


class scenario1:
    drone = Drone()
    drone.pair()
    print("Drone has paired!")
    drone.set_trim(-10, -0.5)
    drone.takeoff()
    drone.set_throttle(20)
    drone.move(1.8)
    time.sleep(0.5)
    drone.hover(1)
    drone.set_pitch(40)
    drone.move(2)
    time.sleep(0.25)
    drone.hover(1)
    time.sleep(0.25)
    drone.move_left(500, "cm", 1)
    drone.hover(1)
    time.sleep(0.5)
    drone.move_backward(320, "cm", 1)
    drone.hover(1)
    time.sleep(0.25)
    drone.move_right(500, "cm", 1)
    drone.hover(1)
    time.sleep(0.5)
    drone.move_forward(200, "cm", 1)
    drone.hover(1)
    time.sleep(0.5)
    #drone.set_throttle(26)
    drone.move(1.6)
    drone.move_forward(30.5, "cm", 1)
    print(drone.get_pos_z(unit="in"))
    print(drone.get_height(unit="in"))
    time.sleep(2)
    drone.hover(2)
    drone.move_forward(75, units="cm", speed=1)
    drone.hover(1)
    time.sleep(0.25)
    drone.move_left(75, "cm", 1)
    drone.hover(1)
    time.sleep(0.5)
    drone.move_backward(75, "cm", 1)
    drone.hover(1)
    time.sleep(0.25)
    drone.move_right(75, "cm", 1)
    drone.hover(1)
    time.sleep(0.25)
    drone.move_forward(75, "cm", 1)
    drone.hover(1)
    time.sleep(1)
    drone.land()
    exit()


def dronescen1c(self):
    print("Now performing scenario 1c...")
    drone = Drone()
    drone.pair()
    print("Drone has paired!")
    drone.set_trim(-10, -0.5)
    drone.takeoff()
    drone.set_throttle(10)
    drone.move(1.8)
    time.sleep(0.5)
    drone.hover(1)
    drone.set_pitch(40)
    drone.move(2)
    drone.hover(1)
    drone.circle(55, 1)
    drone.hover(1)
    drone.move_forward(50, units="in", speed=1)
    drone.hover(1)
    drone.land()
    exit()
